const my_projects = [
  {
    id: 1,
    thumbnail: "/p-2.png",
    title: "Medical Equipment company landing page.",
    link: "https://medicomagic.com/",
    date: "18 Nov 2023",
    tech_skills: "Nextjs-(Pages Router) , CSS3 & Javascript",
    description: "",
  },
  {
    id: 21,
    thumbnail: "/p-21.png",
    title: "Fun Mail.",
    link: "https://fun-mail.vercel.app/",
    date: "3 Nov 2024",
    tech_skills: "Next.js, mail.tm api , Tailwind css and Typescript",
    description: "Your Instant, Disposable Inbox for a Spam-Free Life!",
    type: "personal",
  },
  {
    id: 22,
    thumbnail: "/p-22.png",
    title: "The Vibrant Post.",
    link: "https://the-vibrant-post.vercel.app",
    date: "20 Oct 2024",
    tech_skills: "Next.js, Puppeteer api , Tailwind css and Typescript",
    description: "A simple application that scrape data from BBC.com & Newyork times",
    type: "personal",
  },
  {
    id: 4,
    thumbnail: "/p-1.png",
    title: "Form Builder.",
    link: "https://dynamic-form-generator-six.vercel.app/",
    date: "15 Oct 2023",
    tech_skills: "Next.js, localstorage, Css and Material UI",
    description: "",
    type: "personal",
  },
  {
    id: 12,
    title: "Drag & Drop Board like Asana",
    thumbnail: "/p-5.png",
    link: "https://assignment-mercor-frontend.vercel.app/",
    date: "16 July 2023",
    tech_skills: "React.js & Material UI & react-dnd",
    description: "",
    type: "personal",
  },
  {
    id: 2,
    title: "Event Management Website.",
    thumbnail: "/p-3.png",
    tech_skills: "HTML, CSS, Bootstrap & Javascript",
    date: "05 Sep 2023",
    link: "https://yashpatelllc.com/",
    description: "",
  },
  {
    id: 3,
    title: "Event Management Website.",
    thumbnail: "/project_2.jpg",
    tech_skills: "HTML, CSS, Bootstrap & Javascript",
    date: "20 Apr 2023",
    link: "https://www.deomllc.com/",
    description: "",
  },

  // {
  //   id: 5,
  //   thumbnail: "",
  //   link: "https://origo-assignment.vercel.app/",
  //   date: "20 03 2023",
  //   tech_skills: "React.js & Material UI",
  //   description: "",
  //   type: "personal",
  // },

  {
    id: 6,
    title: "Landing page for tech company.",
    thumbnail: "/p-4.jpg",
    link: "https://www.kwikcoderstechnologies.com/",
    date: "16 March 2023",
    tech_skills: "Next.js & Material UI",
    description: "",
  },
  {
    id: 7,
    title: "Fashion website landing page.",
    thumbnail: "/p-6.png",
    link: "https://fashion-website-jet.vercel.app/",
    date: "13 Jan 2023",
    tech_skills: "React.js and Material UI",
    description: "",
    type: "personal",
  },
  {
    id: 8,
    thumbnail: "/p-7.jpg",
    title: "Basic Store ui [incomplete].",
    link: "https://redux-store-six.vercel.app/",
    date: "10 May 2022",
    tech_skills: "React.js,Redux, Html/Css & Javascript",
    description: "",
    type: "personal",
  },
  {
    id: 9,
    thumbnail: "/p-8.jpg",
    title: "Myntra homepage clone.",
    link: "https://myntra-clone-beta.vercel.app/",
    date: "01 June 2022",
    tech_skills: "HTML/CSS & Javscript",
    description: "",
    type: "personal",
  },
  {
    id: 10,
    thumbnail: "/p-9.png",
    title: "Google Notes Clone [UI].",
    link: "https://google-keep-react-ochre.vercel.app/",
    date: "17 March 2022",
    tech_skills: "React.js & CSS & Javascript",
    description: "",
    type: "personal",
  },
  {
    id: 11,
    thumbnail: "/p-10.png",
    title: "Todo List.",
    link: "https://keep-notes-sigma.vercel.app/",
    date: "09 Feb 2022",
    tech_skills: "React.js & CSS & Javascript",
    description: "",
    type: "personal",
  },
];
export { my_projects };
